/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BurpSuiteExtension3;


import burp.api.montoya.BurpExtension;
import burp.api.montoya.MontoyaApi;

public class ExtensionDemo implements BurpExtension{

    @Override
    public void initialize(MontoyaApi api) {
        //Setting the name for the Extension.
        api.extension().setName("Demo 3");
        api.http().registerHttpHandler(new HttpReqRes(api));
        api.proxy().registerRequestHandler(new HttpProxyReq(api));
        api.proxy().registerResponseHandler(new HttpProxyResp(api));
    }
    
}
